{% set ucx_version = "1.6.0" %}
{% set ucx_proc_version = "1.0.0" %}
{% set number = "0" %}

{% set ucx_proc_type = "cpu" if cuda_compiler_version == "None" else "gpu" %}


package:
  name: ucx-split

source:
  url: https://github.com/openucx/ucx/releases/download/v{{ ucx_version }}/ucx-{{ ucx_version }}.tar.gz
  sha256: 360e885dd7f706a19b673035a3477397d100a02eb618371697c7f3ee4e143e2c
  patches:
    - fixes_4218.patch

build:
  skip: true  # [not linux]
  number: 0

outputs:
  - name: ucx-proc
    version: {{ ucx_proc_version }}
    build:
      number: 0
      string: "{{ ucx_proc_type }}"
    test:
      commands:
        - exit 0
    about:
      home: https://github.com/conda-forge/ucx-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU UCX build.

  - name: ucx
    version: {{ ucx_version }}
    build:
      number: {{ number }}
      string: "h{{ PKG_HASH }}_{{ number }}_{{ ucx_proc_type }}"
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}         # [cuda_compiler_version != "None"]
        - {{ cdt("libnl") }}
        - {{ cdt("libibverbs-devel") }}
        - {{ cdt("librdmacm-devel") }}
        - {{ cdt("numactl-devel") }}
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
      run_constrained:
        - ucx-proc * {{ ucx_proc_type }}
    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        - ${PREFIX}/bin/ucx_info -v         # [cuda_compiler_version == "None"]
    about:
      home: https://github.com/openucx/ucx
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.

about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.

extra:
  recipe-maintainers:
    - Akshay-Venkatesh
    - jakirkham
    - TomAugspurger
